### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [b-t-k/p-g-wodehouse_jeeves-stories#1]
- local.css:

    - When setting margin: auto on blockquote.note, we don't want to override the browser's default top and bottom margins. So instead of doing margin: 1em auto, you should do: margin-left: auto; margin-right: auto;

    - We never want to use classes for presentational styling, so the center class has to be removed. There are more clever ways of targeting those few items that need centering. Remember you can use the story IDs to target too.

    - What's the purpose of the style on line 22?

- content.opf: production notes appears to be cut off?

- Each short story section needs the semantic "volume se:short story", they are not chapters.

- In the metropolitan touch, in "What HO, Twing!!", HO should be in small caps

- In the purity of the turf, in "EE-ee-ee-ee-ee! Oo-ee! Ee-ee-ee-ee!", "EE" should be in small caps

**Comment by b-t-k** [comment]
I suck at "clean" css. Do these changes work?  That bit of code was to change the first line indent on the list to a hanging indent for when the page shrunk. This is the note I am trying to recreate.

https://archive.org/details/in.ernet.dli.2015.509243/page/n124 
I also reused the .note class to format the poster at  https://archive.org/details/in.ernet.dli.2015.509243/page/n173

I hav no idea what I originally wrote for the production notes. I think I cut it to write the editor's preface as most of it is now covered in the editor's preface — so I just added a quick note about future variations in the text. It could probably be deleted altogether.

**Comment by acabal** [comment]
Well, the problem is that now the contents of the notes are not semantically correct. You're putting a quotation in a quotation, and adding `class="list"`, but why are we adding `class="list"` to a blockquote when we could just use an `<ul>` which means "list" semantically?

Here's a better way of doing it in The Great Sermon Handicap. Convert the `blockquote class="note"` to `<ul>` and style it to remove bullets. Then remove the last nested blockquote and target that `p` with `#the-last-sermon-handicap blockquote p:last-child{ text-align: center; text-indent: 0 }`.

**Comment by b-t-k** [comment]
Ok, how about this. I changed the enclosing blockquotes for the two stories to <blockquote id="note"> and added the <ul> for the two bits of the great sermon handicap list that need to be right justified. Then changed the css to:

#note {text-align: center; width: 80%; margin-left: auto; margin-right: auto;}
#note ul {list-style-type: none; text-align: left;}

That centers both the poster and the betting note on the page, centers the appropriate text but left justifies the list part within the centered betting note.

**Comment by acabal** [comment]
Can you format that? You have to escape the code otherwise it's not readable.

**Comment by b-t-k** [comment]
Ok, how about this. I changed the enclosing blockquotes for the two stories to
`<blockquote id="note">`
and added the `<ul>` for the two bits of the great sermon handicap list that need to be right justified. Then changed the css to:
```
#note {text-align: center; width: 80%; margin-left: auto; margin-right: auto;}
#note ul {list-style-type: none; text-align: left;}

```
That centers both the poster and the betting note on the page, centers the appropriate text but left justifies the list part within the centered betting note.

**Comment by acabal** [comment]
But... now you're adding an ID that is just a style hook. IDs are for navigation anchors in the document, not for style hooks. What's wrong with my suggestion?

**Comment by b-t-k** [comment]
What I am tempting to do (and maybe its just impossible) is:

- Center the whole note on the page
- center the first line
- left justify the next bit within the centered note
- center the next line
- left justify the last line

Then I have to deal with the poster in The Metropolitan Touch which just needs to be centered but I thought it should be within a blockquote centered on the page as well so I was using the above solution for efficiency sake.

Your solution  would have had everything left justified  on the page and the last line centered. I did  try to make p's and childs work but it got unwieldy ...but maybe that's still a better way to go?

**Comment by acabal** [comment]
This is all possible with some clever CSS. Check the nth-child selector to target specific elements that may not be targetable in other ways.

**Comment by b-t-k** [comment]
The part I am confused about is the target. This is currently one blockquote among many i the story. As it seems neither class nor id work (and I am really clueless as to why—time for more reading I guess), I can't target that specific blockquote. If I make the whole thing a UL then that works using the story id, but then I lose the ability to treat it as a blockquote.

Is there an obvious thing I am missing or do I just try and make the ul work?

**Comment by b-t-k** [comment]
Here's my current solution: 
`#the-great-sermon-handicap ul {
	width: 80%;
	margin-left: auto;
	margin-right: auto;
}

#the-great-sermon-handicap li {
	list-style-type: none;
	text-align: left;
	text-indent: -1em;
}

#the-great-sermon-handicap ul > p:first-child,
#the-great-sermon-handicap ul > p:last-of-type {
	text-align: center;
	text-indent: 0
}

#the-metropolitan-touch ul {
	list-style-type: none;
	text-align: center;
	text-indent: 0
}`

Still not sure why targeting a specific blockquote rather than relying on the uniqueness of a ul is less "elegant" :-)

**Comment by acabal** [comment]
OK I'm not being clear enough I think. I've updated the CSS myself, you can take a look for an example of how to semantically structure these kinds of things and then style them without using classes or IDs as style hooks.

**Comment by b-t-k** [comment]
Ahhhhh... That _is_ clever... This is why learning how to hack other people's code rather than learning it correctly from the start is a bad thing.

Thanks for your patience.
